#!/bin/bash

# Install the latest version of the Braingeneers Python package from GitHub
#${NB_PYTHON_PREFIX}/bin/pip install --no-cache git+https://github.com/braingeneers/braingeneerspy.git#egg=braingeneers[data,iot,analysis,ml]
#pip install braingeneerspy
${NB_PYTHON_PREFIX}/bin/pip install --no-cache git+https://github.com/braingeneers/braingeneerspy.git#egg=braingeneers[data,iot,analysis,ml]

# Install homework datasets from S3
# This script will download the datasets from S3 and place them in the correct directory structure
# This script should be run from the root of the repository

# Define the base directory path
base_dir="${HOME}/data/ephys"

# Create the base directory
mkdir -p "$base_dir"


# Define an array of dataset names
dataset_names=("2023-08-28-e-Math_Mind_Class/") # Add dataset name here; no commas

# Loop through the dataset names
for sub_dir in "${dataset_names[@]}"; do
  # Create directories
  mkdir -p "$base_dir/$sub_dir"

  # Download data from S3
  aws --endpoint https://s3-west.nrp-nautilus.io s3 cp "s3://braingeneers/ephys/$sub_dir" "$base_dir/$sub_dir" --recursive --no-sign-request
done
